---
- hosts: all
  become: yes
  tasks:
    - include: tasks/selinux_disable.yml
    - include: tasks/yum_update.yml

    - name: install packages
      yum: name={{ item }} state=installed
      with_items:
        - tomcat
        - java-1.8.0-openjdk
        - nginx
        - git

    - name: download gitbucket with check(md5)
      get_url:
        url: https://github.com/gitbucket/gitbucket/releases/download/4.12.1/gitbucket.war
        dest: /var/lib/tomcat/webapps/ROOT.war
        checksum: md5:2e24212116ef2168b229faec5de1f438

    - name: configure nginx
      lineinfile:
        dest: /etc/nginx/nginx.conf
        line: 'proxy_pass http://localhost:8080;'
        insertafter: '^[^#]+location / {'

    - name: configure nginx
      lineinfile:
        dest: /etc/nginx/nginx.conf
        line: 'proxy_set_header    Host    $host;
proxy_set_header    X-Real-IP    $remote_addr;
proxy_set_header    X-Forwarded-Host       $host;
proxy_set_header    X-Forwarded-Server    $host;
proxy_set_header    X-Forwarded-For    $proxy_add_x_forwarded_for;
client_max_body_size 50M;

location ~ ^/[^/]+/[^/]+\.git.*$ {
return 301 http://192.168.99.2/git$request_uri;
                }'
        insertbefore: '^[^#]+location / {'

    - name: start nginx
      systemd:
        name: nginx.service
        state: started
        enabled: yes

    - name: start tomcat
      systemd:
        name: tomcat.service
        state: started
        enabled: yes
